M48
; DRILL file KiCad 10.0.4 date 2026-09-02T14:26:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-02T14:26:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X3.51Y-23.3
X9.29Y-23.3
T2
X29.61Y-17.92
X34.69Y-10.3
M30
